version: 2
updates:
- package-ecosystem: docker
  directory: /
  schedule:
    interval: monthly
- package-ecosystem: pip
  directory: /
  schedule:
    interval: monthly
  ignore:
  - dependency-name: "elasticsearch"
    update-types:
      - "version-update:semver-major"
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
