dependencies:
  - datasets~=3.0
  - elasticsearch~=7.0
  - elasticsearch-dsl~=7.0
  - fasttext~=0.9.2
  - nltk~=3.9
  - numpy~=2.1
  - pandas~=2.2
  - pydantic~=2.9
  - python-dotenv~=1.0
  - pytorch~=2.4
  - pyyaml~=6.0
  - transformers~=4.45
