dependencies:
  - conda-forge::datasets~=3.0
  - conda-forge::elasticsearch~=7.0
  - conda-forge::elasticsearch-dsl~=7.0
  - conda-forge::fasttext~=0.9.2
  - conda-forge::nltk~=3.9
  - conda-forge::numpy~=2.0
  - conda-forge::pandas~=2.2
  - conda-forge::pydantic~=2.9
  - conda-forge::python-dotenv~=1.0
  - pytorch::pytorch~=2.4
  - conda-forge::pyyaml~=6.0
  - conda-forge::spacy~=3.7.1
  - conda-forge::spacy-model-en_core_web_lg~=3.7.1
  - conda-forge::spacy-model-en_core_web_sm~=3.7.1
  - conda-forge::transformers~=4.45
